name: shop_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shop:
    path: '../../packages/features/shop'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
