name: today_question
description: Today Question domain module
version: 0.1.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  go_router: ^17.0.0
  
  # Internal dependencies
  lt_uicomponent:
    path: ../../core/lt_uicomponent
  feature_core:
    path: ../feature_core
  
  # Domain & Data dependencies
  reflection_domain:
    path: ../../domain/reflection_domain
  reflection_data:
    path: ../../data/reflection_data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^4.0.0+1
