name: ltapp_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Flutter 核心依赖
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  go_router: ^17.0.0
  intl: ^0.20.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  dio: ^5.9.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.4.1
  flutter_secure_storage: ^10.0.0
  scroll_to_index: ^3.0.1
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.5
  web3dart: ^2.7.3
  http: ^1.6.0

  # Core Packages
  lt_uicomponent:
    path: ../../packages/core/lt_uicomponent
  lt_network:
    path: ../../packages/core/network

  # Clean Architecture Layers - Domain
  reflection_domain:
    path: ../../packages/domain/reflection_domain
  user_domain:
    path: ../../packages/domain/user_domain
  wallet_domain:
    path: ../../packages/domain/wallet_domain

  # Clean Architecture Layers - Data
  reflection_data:
    path: ../../packages/data/reflection_data
  user_data:
    path: ../../packages/data/user_data
  wallet_data:
    path: ../../packages/data/wallet_data

  # Utility Packages
  date_utl:
    path: ../../packages/utls/date_utl
  lt_annotation:
    path: ../../packages/utls/lt_annotation

  # Feature Packages
  add_answer:
    path: ../../packages/features/add_answer
  answer_detail:
    path: ../../packages/features/answer_detail
  calendar:
    path: ../../packages/features/calendar
  copilot:
    path: ../../packages/features/copilot
  feature_core:
    path: ../../packages/features/feature_core
  thread:
    path: ../../packages/features/thread
  today_question:
    path: ../../packages/features/today_question
  user:
    path: ../../packages/features/user



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^4.0.0+1
  freezed: ^3.2.3
  json_serializable: ^6.7.1

# flutter:
#   uses-material-design: true
#   assets:
#     - assets/icons/
#   fonts:
#     - family: Poppins
#       fonts:
#         - asset: assets/fonts/Poppins-Regular.ttf

#     - family: FeltTipSeniorRegular
#       fonts:
#         - asset: assets/fonts/FeltTipSeniorRegular.ttf
        
#     - family: PoppinsMediumItalic
#       fonts:
#         - asset: assets/fonts/Poppins-MediumItalic.ttf

#     - family: VividlyRegular
#       fonts:
#         - asset: assets/fonts/VividlyRegular.ttf